#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAE2536227F69F181 (hs@ox.cx)
#
Name     : attrs
Version  : 19.1.0
Release  : 35
URL      : https://files.pythonhosted.org/packages/cc/d9/931a24cc5394f19383fbbe3e1147a0291276afa43a0dc3ed0d6cd9fda813/attrs-19.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/cc/d9/931a24cc5394f19383fbbe3e1147a0291276afa43a0dc3ed0d6cd9fda813/attrs-19.1.0.tar.gz
Source99 : https://files.pythonhosted.org/packages/cc/d9/931a24cc5394f19383fbbe3e1147a0291276afa43a0dc3ed0d6cd9fda813/attrs-19.1.0.tar.gz.asc
Summary  : Classes Without Boilerplate
Group    : Development/Tools
License  : MIT
Requires: attrs-license = %{version}-%{release}
Requires: attrs-python = %{version}-%{release}
Requires: attrs-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-core
BuildRequires : setuptools-legacypython
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://www.attrs.org/en/latest/_static/attrs_logo.png
:alt: attrs Logo

%package license
Summary: license components for the attrs package.
Group: Default

%description license
license components for the attrs package.


%package python
Summary: python components for the attrs package.
Group: Default
Requires: attrs-python3 = %{version}-%{release}

%description python
python components for the attrs package.


%package python3
Summary: python3 components for the attrs package.
Group: Default
Requires: python3-core

%description python3
python3 components for the attrs package.


%prep
%setup -q -n attrs-19.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558024598
export GCC_IGNORE_WERROR=1
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/attrs
cp LICENSE %{buildroot}/usr/share/package-licenses/attrs/LICENSE
cp docs/license.rst %{buildroot}/usr/share/package-licenses/attrs/docs_license.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/attrs/LICENSE
/usr/share/package-licenses/attrs/docs_license.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
